library('parallel')

ptm <- proc.time()
tic()
mutans_coupling_vector_list <- GRB_generate_set_lists_cluster(mutans, 1:10, compare_known_r0_sets = TRUE, optimize_suppr=TRUE)
toc()
print(proc.time() - ptm)

ptm <- proc.time()
tic()
mutans_coupling_vector_list <- GRB_generate_set_lists_cluster(mutans, 1:10, compare_known_r0_sets = TRUE, optimize_suppr=TRUE, cores = 2)
toc()
print(proc.time() - ptm)

ptm <- proc.time()
tic()
mutans_coupling_vector_list <- GRB_generate_set_lists_cluster(mutans, 1:10, compare_known_r0_sets = TRUE, optimize_suppr=TRUE, cores = 4)
toc()
print(proc.time() - ptm)

ptm <- proc.time()
tic()
mutans_coupling_vector_list <- GRB_generate_set_lists_cluster(mutans, 1:10, compare_known_r0_sets = TRUE, optimize_suppr=TRUE, cores = 8)
toc()
print(proc.time() - ptm)
